version: '3.8'

services:
  # Relational Database Service
  mysql_db:
    image: mysql:8.0
    container_name: janvoice_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: janvoice_ai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
